[package]
name = "quest"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "3.0.0"
directories = "6.0.0"
rusqlite = { version = "0.33.0", features = ["bundled"] }
